name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn clean package

      - name: Get Version
        run: MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/keycloak-to-activemq-*.jar
          tag_name: $MVN_VERSION
          generate_release_notes: true

      - name: Bump Version
        run: mvn release:update-versions -B

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5